-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  order_items

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NULL,
  book_id BIGINT NULL,
  product_ref INTEGER NULL,
  title_snapshot VARCHAR(255) NOT NULL,
  sku_snapshot VARCHAR(64) NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  quantity INTEGER NOT NULL,
  tax_rate NUMERIC(5,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_order_items_qty CHECK (quantity > 0),
  CONSTRAINT chk_order_items_currency CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_order_items_tax_rate CHECK (tax_rate BETWEEN 0 AND 100),
  CONSTRAINT chk_order_items_nonneg CHECK (unit_price >= 0)
);
